<a href="https://colab.research.google.com/github/shkimusw/bigdata/blob/main/%5B9%EC%A3%BC%EC%B0%A8_%EA%B0%95%EC%9D%98%5D_numpy_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기본 기능

In [ ]:
import numpy as np
print(np.sqrt(2))

1.4142135623730951


In [ ]:
import numpy as np
print(np.power(2,4))
print(np.power(3,3))

In [ ]:
import numpy as np
print(np.pi)
print(np.sin(0))
print(np.cos(np.pi))

In [ ]:
#랜덤 함수
import numpy as np
a=np.random.rand(5) #0~1 사이 랜덤 실수 5개
print(a)


In [ ]:
print(np.random.choice(6,10)) # 0~5 사이 정수 10개 선택

In [ ]:
print(np.random.choice(10,6, replace=False))  #이미 뽑은 숫자 안 뽑기

In [ ]:
print(np.random.choice(6,10,p=[0.1,0.2,0.3,0.2,0.1,0.1])) #p로 0~5 숫자 나올 확률 지정

# 그래프 그리기 (p.211)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
dice=np.random.choice(6,10)

plt.hist(dice,bins=6)
plt.show()

In [ ]:
#위에서 지정한 확률 그래프로 확인해보기
histogram=np.random.choice(6,1000000,p=[0.1,0.2,0.3,0.2,0.1,0.1])
plt.hist(histogram, bins=6)
plt.show()

# 배열 생성하기

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a) #array에 쉼표가 없다는 것 확인

In [ ]:
print(a[1], a[-1])

In [ ]:
print(a[1:])

In [ ]:
b=np.array([1,2,'3',4]) #3만 문자로 저장
print(b) # 모두 문자로 저장되는 것 확인

In [ ]:
c=np.zeros(10) #0으로 이루어진 크기가 10인 배열
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
d=np.ones(10) #1으로 이루어진 크기가 10인 배열
print(d)

In [ ]:
e=np.zeros(10)+5 #초기값 5인 배열 10개
print(e)

In [ ]:
f=np.linspace(1,2,11) #1~2를 11개의 구간으로 나눈 실수 배열
print(f)
print(np.sqrt(f))

In [ ]:
g=np.arange(-5,5)
print(g)
print(g>0)


In [ ]:
print(g[g>0])

행렬연산

In [ ]:
ar1=np.array([1,2,3,4,5])
ar2=np.array([[10,20,30],[40,50,60]])
ar2

In [ ]:
ar3=np.array([1,2,3,4,5,6]).reshape((3,2))   #3행 2열로 구조변경
ar3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
ar4=np.zeros((2,3))  #2행 3열의 0
ar4

In [ ]:
ar5=ar1+10
ar5

In [ ]:
ar1+ar5

In [ ]:
ar5-ar1

In [ ]:
ar1*2

In [ ]:
ar1/2

In [ ]:
ar6=np.dot(ar2,ar3)
ar6

array([[220, 280],
       [490, 640]])